name: docker

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/docker.yml'
      - 'Dockerfile'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        load: [ true, false ]
        image: [ '0yi0/local:ubuntu_with_figlet' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          tags: ${{ matrix.image }}
          load: ${{ matrix.load }}
      - id: test
        continue-on-error: true
        shell: bash
        run: |
          docker run --rm ${{ matrix.image }} figlet hello world
      - if: steps.test.outcome != 'success'
        run: exit ${{ matrix.load && '1' || '0' }}
