name: github-script summary

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/gh-script-summary.yml'

jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const tableData = [
              {data: 'Header1', header: true},
              {data: 'Header2', header: true},
              {data: 'Header3', header: true},
              {data: 'MyData1'},
              {data: 'MyData2'},
              {data: 'MyData3'}
            ]
            core.summary.addTable([tableData])
            core.summary.write()
